### ISSUE TITLE
Type normalization

### ISSUE THREAD

**Issue by HalfVoxel** [DarthPumpkin/github-search#1]
Should normalize types that are commonly interchanged.
E.g List<T> ≈ ArrayList<T> ≈ T[]
Integer ≈ int ≈ long
etc.

E.g we could collapse all list like things to "List" and all integer values to "Integer" and all floating point values to "Float" etc.

**Comment by DarthPumpkin** [comment]
d19392c22b72a59efd02f0a3d83c16ad6082edf3
